---
- hosts: all
  tasks:
  - name: Installing apache2
    yum: 
      name: httpd
      state: latest
  - name: create webpage
    copy:
      src: index.html
      dest: /var/www/html/index.html 
  - name: starting a service 
    service:
      name: httpd
      state: restarted
      enabled: true 